apiVersion: apps/v1
kind: Deployment
metadata:
  name: makerspacebonn-discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makerspacebonn-discord-bot
  template:
    metadata:
      labels:
        app: makerspacebonn-discord-bot
    spec:
      containers:
        - name: makerspacebonn-discord-bot
          image: ghcr.io/lxfrdl/makerspacebonn-discord-bot:77b8715d0c5a497fc04002aeb1e3d6bb9879e085
          ports:
            - containerPort: 8080
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN